# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

#spark.sql("USE CATALOG `<my-catalog>`")
spark.sql("USE SCHEMA `bookstore_etl_pro`")

# COMMAND ----------

spark.sql("use catalog workspace")
spark.sql("use schema bookstore_etl_pro")

df = spark.sql("select current_catalog(), current_schema()")
display(df.collect()[0][0], ",", df.collect()[0][1])

# COMMAND ----------

display(spark.sql("SELECT count(*) FROM bronze"))

# COMMAND ----------


